// Currency patterns for detection
export const CURRENCY_PATTERNS: Record<string, RegExp> = {
  USD: /\b(usd|dollar|dollars|\$)\b/i,
  EUR: /\b(eur|euro|euros|€)\b/i,
  USDC: /\b(usdc|usd coin)\b/i,
  GBP: /\b(gbp|pound|pounds|£)\b/i,
  PHP: /\b(php|peso|pesos)\b/i,
  MAD: /\b(mad|dirham|dirhams)\b/i,
  NGN: /\b(ngn|naira)\b/i,
  INR: /\b(inr|rupee|rupees)\b/i,
  CNY: /\b(cny|yuan|renminbi)\b/i,
  JPY: /\b(jpy|yen)\b/i,
  CAD: /\b(cad|canadian dollar)\b/i,
  AUD: /\b(aud|australian dollar)\b/i,
  MXN: /\b(mxn|mexican peso)\b/i,
  BRL: /\b(brl|real|reais)\b/i,
  KRW: /\b(krw|won)\b/i,
  SGD: /\b(sgd|singapore dollar)\b/i,
  THB: /\b(thb|baht)\b/i,
  VND: /\b(vnd|dong)\b/i,
  IDR: /\b(idr|rupiah)\b/i,
  MYR: /\b(myr|ringgit)\b/i,
  ZAR: /\b(zar|rand)\b/i,
  EGP: /\b(egp|egyptian pound)\b/i,
  KES: /\b(kes|kenyan shilling)\b/i,
  GHS: /\b(ghs|cedi)\b/i,
  PKR: /\b(pkr|pakistani rupee)\b/i,
  BDT: /\b(bdt|taka)\b/i,
  TRY: /\b(try|lira)\b/i,
  PLN: /\b(pln|zloty)\b/i,
  CHF: /\b(chf|swiss franc)\b/i,
  SEK: /\b(sek|krona)\b/i,
  NOK: /\b(nok|krone)\b/i,
  DKK: /\b(dkk|krone)\b/i,
  NZD: /\b(nzd|new zealand dollar)\b/i,
  RUB: /\b(rub|ruble)\b/i,
  UAH: /\b(uah|hryvnia)\b/i,
  ILS: /\b(ils|shekel)\b/i,
  SAR: /\b(sar|riyal)\b/i,
  AED: /\b(aed|dirham)\b/i,
  QAR: /\b(qar|riyal)\b/i,
  KWD: /\b(kwd|dinar)\b/i,
  BHD: /\b(bhd|dinar)\b/i,
  OMR: /\b(omr|rial)\b/i,
  JOD: /\b(jod|dinar)\b/i,
  LBP: /\b(lbp|pound)\b/i,
  IQD: /\b(iqd|dinar)\b/i,
  IRR: /\b(irr|rial)\b/i,
  AFN: /\b(afn|afghani)\b/i,
  LKR: /\b(lkr|rupee)\b/i,
  NPR: /\b(npr|rupee)\b/i,
  MMK: /\b(mmk|kyat)\b/i,
  KHR: /\b(khr|riel)\b/i,
  LAK: /\b(lak|kip)\b/i,
  MNT: /\b(mnt|tugrik)\b/i,
  TWD: /\b(twd|dollar)\b/i,
  HKD: /\b(hkd|dollar)\b/i,
  MOP: /\b(mop|pataca)\b/i,
  BND: /\b(bnd|dollar)\b/i,
};
