// Country name to ISO 3166-1 alpha-2 code mapping
export const countryMap: Record<string, string> = {
  // Major countries
  'united states': 'US',
  'usa': 'US',
  'us': 'US',
  'america': 'US',
  'philippines': 'PH',
  'ph': 'PH',
  'manila': 'PH',
  'morocco': 'MA',
  'ma': 'MA',
  'nigeria': 'NG',
  'ng': 'NG',
  'united kingdom': 'GB',
  'uk': 'GB',
  'britain': 'GB',
  'england': 'GB',
  'canada': 'CA',
  'ca': 'CA',
  'australia': 'AU',
  'au': 'AU',
  'india': 'IN',
  'in': 'IN',
  'china': 'CN',
  'cn': 'CN',
  'japan': 'JP',
  'jp': 'JP',
  'germany': 'DE',
  'de': 'DE',
  'france': 'FR',
  'fr': 'FR',
  'spain': 'ES',
  'es': 'ES',
  'italy': 'IT',
  'it': 'IT',
  'brazil': 'BR',
  'br': 'BR',
  'mexico': 'MX',
  'mx': 'MX',
  'argentina': 'AR',
  'ar': 'AR',
  'south korea': 'KR',
  'korea': 'KR',
  'kr': 'KR',
  'singapore': 'SG',
  'sg': 'SG',
  'thailand': 'TH',
  'th': 'TH',
  'vietnam': 'VN',
  'vn': 'VN',
  'indonesia': 'ID',
  'id': 'ID',
  'malaysia': 'MY',
  'my': 'MY',
  'south africa': 'ZA',
  'za': 'ZA',
  'egypt': 'EG',
  'eg': 'EG',
  'kenya': 'KE',
  'ke': 'KE',
  'ghana': 'GH',
  'gh': 'GH',
  'pakistan': 'PK',
  'pk': 'PK',
  'bangladesh': 'BD',
  'bd': 'BD',
  'turkey': 'TR',
  'tr': 'TR',
  'poland': 'PL',
  'pl': 'PL',
  'netherlands': 'NL',
  'nl': 'NL',
  'belgium': 'BE',
  'be': 'BE',
  'switzerland': 'CH',
  'ch': 'CH',
  'sweden': 'SE',
  'se': 'SE',
  'norway': 'NO',
  'no': 'NO',
  'denmark': 'DK',
  'dk': 'DK',
  'finland': 'FI',
  'fi': 'FI',
  'portugal': 'PT',
  'pt': 'PT',
  'greece': 'GR',
  'gr': 'GR',
  'ireland': 'IE',
  'ie': 'IE',
  'new zealand': 'NZ',
  'nz': 'NZ',
  'chile': 'CL',
  'cl': 'CL',
  'colombia': 'CO',
  'co': 'CO',
  'peru': 'PE',
  'pe': 'PE',
  'venezuela': 'VE',
  've': 'VE',
  'ecuador': 'EC',
  'ec': 'EC',
  'uruguay': 'UY',
  'uy': 'UY',
  'paraguay': 'PY',
  'py': 'PY',
  'bolivia': 'BO',
  'bo': 'BO',
  'costa rica': 'CR',
  'cr': 'CR',
  'panama': 'PA',
  'pa': 'PA',
  'guatemala': 'GT',
  'gt': 'GT',
  'honduras': 'HN',
  'hn': 'HN',
  'el salvador': 'SV',
  'sv': 'SV',
  'nicaragua': 'NI',
  'ni': 'NI',
  'dominican republic': 'DO',
  'do': 'DO',
  'jamaica': 'JM',
  'jm': 'JM',
  'trinidad and tobago': 'TT',
  'tt': 'TT',
  'barbados': 'BB',
  'bb': 'BB',
  'bahamas': 'BS',
  'bs': 'BS',
  'cuba': 'CU',
  'cu': 'CU',
  'haiti': 'HT',
  'ht': 'HT',
  'puerto rico': 'PR',
  'pr': 'PR',
  'russia': 'RU',
  'ru': 'RU',
  'ukraine': 'UA',
  'ua': 'UA',
  'belarus': 'BY',
  'by': 'BY',
  'kazakhstan': 'KZ',
  'kz': 'KZ',
  'uzbekistan': 'UZ',
  'uz': 'UZ',
  'israel': 'IL',
  'il': 'IL',
  'saudi arabia': 'SA',
  'sa': 'SA',
  'uae': 'AE',
  'united arab emirates': 'AE',
  'ae': 'AE',
  'qatar': 'QA',
  'qa': 'QA',
  'kuwait': 'KW',
  'kw': 'KW',
  'bahrain': 'BH',
  'bh': 'BH',
  'oman': 'OM',
  'om': 'OM',
  'jordan': 'JO',
  'jo': 'JO',
  'lebanon': 'LB',
  'lb': 'LB',
  'iraq': 'IQ',
  'iq': 'IQ',
  'iran': 'IR',
  'ir': 'IR',
  'afghanistan': 'AF',
  'af': 'AF',
  'sri lanka': 'LK',
  'lk': 'LK',
  'nepal': 'NP',
  'np': 'NP',
  'myanmar': 'MM',
  'mm': 'MM',
  'cambodia': 'KH',
  'kh': 'KH',
  'laos': 'LA',
  'la': 'LA',
  'mongolia': 'MN',
  'mn': 'MN',
  'taiwan': 'TW',
  'tw': 'TW',
  'hong kong': 'HK',
  'hk': 'HK',
  'macau': 'MO',
  'mo': 'MO',
  'brunei': 'BN',
  'bn': 'BN',
  'east timor': 'TL',
  'tl': 'TL',
  'papua new guinea': 'PG',
  'pg': 'PG',
  'fiji': 'FJ',
  'fj': 'FJ',
  'samoa': 'WS',
  'ws': 'WS',
  'tonga': 'TO',
  'to': 'TO',
  'vanuatu': 'VU',
  'vu': 'VU',
  'solomon islands': 'SB',
  'sb': 'SB',
  'palau': 'PW',
  'pw': 'PW',
  'micronesia': 'FM',
  'fm': 'FM',
  'marshall islands': 'MH',
  'mh': 'MH',
  'kiribati': 'KI',
  'ki': 'KI',
  'nauru': 'NR',
  'nr': 'NR',
  'tuvalu': 'TV',
  'tv': 'TV',
};

// Currency to local currency mapping for corridors
export const currencyToLocalCurrency: Record<string, Record<string, string>> = {
  'USD': {
    'PH': 'PHP',
    'NG': 'NGN',
    'IN': 'INR',
    'CN': 'CNY',
    'JP': 'JPY',
    'GB': 'GBP',
    'EU': 'EUR',
    'CA': 'CAD',
    'AU': 'AUD',
    'MX': 'MXN',
    'BR': 'BRL',
    'KR': 'KRW',
    'SG': 'SGD',
    'TH': 'THB',
    'VN': 'VND',
    'ID': 'IDR',
    'MY': 'MYR',
    'ZA': 'ZAR',
    'EG': 'EGP',
    'KE': 'KES',
    'GH': 'GHS',
    'PK': 'PKR',
    'BD': 'BDT',
    'TR': 'TRY',
    'PL': 'PLN',
    'NL': 'EUR',
    'BE': 'EUR',
    'CH': 'CHF',
    'SE': 'SEK',
    'NO': 'NOK',
    'DK': 'DKK',
    'FI': 'EUR',
    'PT': 'EUR',
    'GR': 'EUR',
    'IE': 'EUR',
    'NZ': 'NZD',
    'CL': 'CLP',
    'CO': 'COP',
    'PE': 'PEN',
    'VE': 'VES',
    'EC': 'USD',
    'UY': 'UYU',
    'PY': 'PYG',
    'BO': 'BOB',
    'CR': 'CRC',
    'PA': 'PAB',
    'GT': 'GTQ',
    'HN': 'HNL',
    'SV': 'USD',
    'NI': 'NIO',
    'DO': 'DOP',
    'JM': 'JMD',
    'TT': 'TTD',
    'BB': 'BBD',
    'BS': 'BSD',
    'CU': 'CUP',
    'HT': 'HTG',
    'PR': 'USD',
    'RU': 'RUB',
    'UA': 'UAH',
    'BY': 'BYN',
    'KZ': 'KZT',
    'UZ': 'UZS',
    'IL': 'ILS',
    'SA': 'SAR',
    'AE': 'AED',
    'QA': 'QAR',
    'KW': 'KWD',
    'BH': 'BHD',
    'OM': 'OMR',
    'JO': 'JOD',
    'LB': 'LBP',
    'IQ': 'IQD',
    'IR': 'IRR',
    'AF': 'AFN',
    'LK': 'LKR',
    'NP': 'NPR',
    'MM': 'MMK',
    'KH': 'KHR',
    'LA': 'LAK',
    'MN': 'MNT',
    'TW': 'TWD',
    'HK': 'HKD',
    'MO': 'MOP',
    'BN': 'BND',
    'TL': 'USD',
    'PG': 'PGK',
    'FJ': 'FJD',
    'WS': 'WST',
    'TO': 'TOP',
    'VU': 'VUV',
    'SB': 'SBD',
    'PW': 'USD',
    'FM': 'USD',
    'MH': 'USD',
    'KI': 'AUD',
    'NR': 'AUD',
    'TV': 'AUD',
    'MA': 'MAD',
  },
  'EUR': {
    'US': 'USD',
    'PH': 'PHP',
    'NG': 'NGN',
    'MA': 'MAD',
    'GB': 'GBP',
    'CA': 'CAD',
    'AU': 'AUD',
    'MX': 'MXN',
    'BR': 'BRL',
    'KR': 'KRW',
    'SG': 'SGD',
    'TH': 'THB',
    'VN': 'VND',
    'ID': 'IDR',
    'MY': 'MYR',
    'ZA': 'ZAR',
    'EG': 'EGP',
    'KE': 'KES',
    'GH': 'GHS',
    'PK': 'PKR',
    'BD': 'BDT',
    'TR': 'TRY',
    'PL': 'PLN',
    'CH': 'CHF',
    'SE': 'SEK',
    'NO': 'NOK',
    'DK': 'DKK',
    'NZ': 'NZD',
    'RU': 'RUB',
    'UA': 'UAH',
    'IL': 'ILS',
    'SA': 'SAR',
    'AE': 'AED',
    'QA': 'QAR',
    'KW': 'KWD',
    'BH': 'BHD',
    'OM': 'OMR',
    'JO': 'JOD',
    'LB': 'LBP',
    'IQ': 'IQD',
    'IR': 'IRR',
    'AF': 'AFN',
    'LK': 'LKR',
    'NP': 'NPR',
    'MM': 'MMK',
    'KH': 'KHR',
    'LA': 'LAK',
    'MN': 'MNT',
    'TW': 'TWD',
    'HK': 'HKD',
    'MO': 'MOP',
    'BN': 'BND',
    'IN': 'INR',
    'CN': 'CNY',
    'JP': 'JPY',
  },
  'USDC': {
    'PH': 'PHP',
    'NG': 'NGN',
    'MA': 'MAD',
    'IN': 'INR',
    'CN': 'CNY',
    'JP': 'JPY',
    'GB': 'GBP',
    'EU': 'EUR',
    'CA': 'CAD',
    'AU': 'AUD',
    'MX': 'MXN',
    'BR': 'BRL',
    'KR': 'KRW',
    'SG': 'SGD',
    'TH': 'THB',
    'VN': 'VND',
    'ID': 'IDR',
    'MY': 'MYR',
    'ZA': 'ZAR',
    'EG': 'EGP',
    'KE': 'KES',
    'GH': 'GHS',
    'PK': 'PKR',
    'BD': 'BDT',
    'TR': 'TRY',
    'PL': 'PLN',
    'NL': 'EUR',
    'BE': 'EUR',
    'CH': 'CHF',
    'SE': 'SEK',
    'NO': 'NOK',
    'DK': 'DKK',
    'FI': 'EUR',
    'PT': 'EUR',
    'GR': 'EUR',
    'IE': 'EUR',
    'NZ': 'NZD',
    'CL': 'CLP',
    'CO': 'COP',
    'PE': 'PEN',
    'VE': 'VES',
    'EC': 'USD',
    'UY': 'UYU',
    'PY': 'PYG',
    'BO': 'BOB',
    'CR': 'CRC',
    'PA': 'PAB',
    'GT': 'GTQ',
    'HN': 'HNL',
    'SV': 'USD',
    'NI': 'NIO',
    'DO': 'DOP',
    'JM': 'JMD',
    'TT': 'TTD',
    'BB': 'BBD',
    'BS': 'BSD',
    'CU': 'CUP',
    'HT': 'HTG',
    'PR': 'USD',
    'RU': 'RUB',
    'UA': 'UAH',
    'BY': 'BYN',
    'KZ': 'KZT',
    'UZ': 'UZS',
    'IL': 'ILS',
    'SA': 'SAR',
    'AE': 'AED',
    'QA': 'QAR',
    'KW': 'KWD',
    'BH': 'BHD',
    'OM': 'OMR',
    'JO': 'JOD',
    'LB': 'LBP',
    'IQ': 'IQD',
    'IR': 'IRR',
    'AF': 'AFN',
    'LK': 'LKR',
    'NP': 'NPR',
    'MM': 'MMK',
    'KH': 'KHR',
    'LA': 'LAK',
    'MN': 'MNT',
    'TW': 'TWD',
    'HK': 'HKD',
    'MO': 'MOP',
    'BN': 'BND',
    'TL': 'USD',
    'PG': 'PGK',
    'FJ': 'FJD',
    'WS': 'WST',
    'TO': 'TOP',
    'VU': 'VUV',
    'SB': 'SBD',
    'PW': 'USD',
    'FM': 'USD',
    'MH': 'USD',
    'KI': 'AUD',
    'NR': 'AUD',
    'TV': 'AUD',
  },
};

export function getCountryCode(location: string): string | null {
  const normalized = location.toLowerCase().trim();
  
  // Direct match (exact)
  if (countryMap[normalized]) {
    return countryMap[normalized];
  }
  
  // For city names that map to countries (like "manila" -> "PH")
  // Only do exact matches to avoid false positives
  // Partial matching is too risky and causes false positives
  
  return null;
}

export function getCorridor(sourceCurrency: string | null, destinationCountry: string | null): string | null {
  if (!sourceCurrency || !destinationCountry) {
    return null;
  }
  
  const localCurrency = currencyToLocalCurrency[sourceCurrency]?.[destinationCountry];
  if (localCurrency) {
    return `${sourceCurrency}-${localCurrency}`;
  }
  
  // Fallback: if we have both, create a basic corridor
  return `${sourceCurrency}-${destinationCountry}`;
}
